---
- name: Налаштування спільних компонентів (користувачі, пакети)
  hosts: all
  become: yes
  roles:
    - common

- name: Налаштування бази даних PostgreSQL
  hosts: db
  become: yes
  roles:
    - db
# - name: Налаштування Node.js застосунку та Nginx
#   hosts: workers
#   become: yes
#   roles:
#     - app
#     - nginx